name: Cleanup Artifacts, Logs, and Cache

on:
  schedule:
    - cron: '0 18 * * *'  # 毎日JST 03:00（UTC換算）
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Delete old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '3 days'
          GITHUB_TOKEN: ${{ github.token }}

      - name: Delete caches
        uses: easimon/wipe-cache@main
        with:
          github-token: ${{ github.token }}
          dry-run: 'false'

      - name: Delete workflow logs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 3
          token: ${{ github.token }}